### PR TITLE
Update website layout

### PR DESCRIPTION
**Pull request by pet-mit**
Added custom html layouts & includes, by copying them from [minimal-mistakes](https://github.com/mmistakes/minimal-mistakes) and modifying them a little to:
- Improve home page look
  - Remove empty sidebar (copied the 'collection' layout, renamed it 'home', simplified it, and made it inherit from 'default' instead of 'archive')
  - Remove titles of projects marked with "show-title: false" (by overriding the 'archive-single' include)
  - Center teaser image vertically and link it to project page (by overriding the 'archive-single' css)
  - Justify project excerpt (by overriding the 'archive-single' include)
- Disable 'Last updated' mention in projects page, since it is not relevant (by modifying the 'project' layout)

Home before:
Screenshot_17-12-2024_182049_rte-france github io

After:
Screenshot_17-12-2024_18214_127 0 0 1

### CODE REVIEW

**Comment by annetill** [comment]
:-) I was about to write you about that :-)

**Comment by pet-mit** [comment]
> @pet-mit by the way, it seems that our main branch is still called "master". It could be nice to change for "main" in the future.

you're right, I can do it once the 2 remaining PRs are merged

**Review by annetill — APPROVED** [review]
Very nice, it works well on my computer. I have pushed some typos. I have an issue with Grid2Op logo : maybe we have to ask for a non-white back-end logo, what do you think ?

**Comment by pet-mit** [comment]
> Very nice, it works well on my computer. I have pushed some typos. I have an issue with Grid2Op logo : maybe we have to ask for a non-white back-end logo, what do you think ? 

I agree that we should work on homogeneous logos. I think grid2op will not be the last project to have a somewhat different logo (all others that are currently on the website have a LFE-style logo) and I didn't want to give them more work / slow down this PR, so I just centered it for now to make it look nicer. 

But we should definitely discuss RTE OSS branding rules for non-LFE projects.

**Pull request merged**
